apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: selenium-hub
    namespace: {{ .Release.Namespace }}
    labels:
        name: selenium-hub
spec:
    strategy:
        type: Recreate
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            name: selenium-hub
    template:
        metadata:
            labels:
                name: selenium-hub
        spec:
            initContainers:
            -   name: selenium-hub
                imagePullPolicy: Always
                image: {{ .Values.hub.image }}:{{ .Values.hub.version }}
                ports:
                -   containerPort: 4444
            terminationGracePeriodSeconds: 0
            containers:
            -   name: node-chrome
                imagePullPolicy: Always
                image: {{ .Values.chrome.image}}:{{ .Values.chrome.version }}
