apiVersion: v1
kind: Service
metadata:
    name: selenium
    namespace: {{ .Release.Namespace }}
    labels:
        name: selenium
spec:
    selector:
        name: selenium-hub
    ports:
    -   port: 80
        targetPort: 4444
