apiVersion: v1
kind: Service
metadata:
    name: jenkins
    namespace: {{ .Release.Namespace }}
    labels:
        name: jenkins
spec:
    selector:
        name: jenkins
    ports:
    -   port: 80
        targetPort: 8080
